version: '3.9'

services:
  web:
    image: my_website_image
    ports:
      - "8080:80"
    networks:
      - web_network

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - db_network

networks:
  web_network:
  db_network:
